-- Disabled: not loaded from custom/plugins/init.lua
-- To enable: add `require 'custom.plugins.ui.barbecue'` to custom/plugins/init.lua

-- local function gh(repo) return 'https://github.com/' .. repo end
-- vim.pack.add {
--   gh 'utilyre/barbecue.nvim',
--   gh 'SmiteshP/nvim-navic',
-- }
-- require('barbecue').setup {
--   attach_navic = true,
--   create_autocmd = true,
--   theme = 'auto',
--   symbols = { modified = '●', ellipsis = '…', separator = '»' },
-- }
